/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.animals;

/**
 *
 * @author Compus
 */
public class FrmViewAnimals extends javax.swing.JFrame {

    /**
     * Creates new form ViewAnimals
     */
    public FrmViewAnimals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTiger = new javax.swing.JButton();
        btnMonkey = new javax.swing.JButton();
        btnLeon = new javax.swing.JButton();
        btnGorilla = new javax.swing.JButton();
        btnElephant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTiger.setText("Tiger");
        btnTiger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTigerActionPerformed(evt);
            }
        });

        btnMonkey.setText("Monkey");
        btnMonkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonkeyActionPerformed(evt);
            }
        });

        btnLeon.setText("Leon");
        btnLeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeonActionPerformed(evt);
            }
        });

        btnGorilla.setText("Gorilla");
        btnGorilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGorillaActionPerformed(evt);
            }
        });

        btnElephant.setText("Elephant");
        btnElephant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElephantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnTiger)
                        .addGap(18, 18, 18)
                        .addComponent(btnMonkey)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeon)
                        .addGap(18, 18, 18)
                        .addComponent(btnGorilla))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnElephant)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTiger)
                    .addComponent(btnMonkey)
                    .addComponent(btnLeon)
                    .addComponent(btnGorilla))
                .addGap(30, 30, 30)
                .addComponent(btnElephant)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTigerActionPerformed
        TigerFeeding newframe = new TigerFeeding();
        newframe.setVisible(true);
    }//GEN-LAST:event_btnTigerActionPerformed

    private void btnMonkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonkeyActionPerformed
        MonkeyFeeding newframe = new  MonkeyFeeding();
        newframe.setVisible(true);
    }//GEN-LAST:event_btnMonkeyActionPerformed

    private void btnLeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeonActionPerformed
        LeonFeeding newframe = new  LeonFeeding();
        newframe.setVisible(true);
    }//GEN-LAST:event_btnLeonActionPerformed

    private void btnGorillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGorillaActionPerformed
       GorillaFeeding newframe = new  GorillaFeeding();
       newframe.setVisible(true);
    }//GEN-LAST:event_btnGorillaActionPerformed

    private void btnElephantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElephantActionPerformed
        ElephantFeeding newframe = new  ElephantFeeding();
        newframe.setVisible(true);
    }//GEN-LAST:event_btnElephantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViewAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViewAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViewAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViewAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmViewAnimals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElephant;
    private javax.swing.JButton btnGorilla;
    private javax.swing.JButton btnLeon;
    private javax.swing.JButton btnMonkey;
    private javax.swing.JButton btnTiger;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
