/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoo.view;

/**
 *
 * @author Administrador
 */
public class frmVisitorMenu extends javax.swing.JFrame {

    /**
     * Creates new form fmrVisitorMenu
     */
    public frmVisitorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        VisitorFName = new javax.swing.JLabel();
        VisitorLName = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        Title2 = new javax.swing.JLabel();
        TitleIdVis = new javax.swing.JLabel();
        IdVis = new javax.swing.JTextField();
        TitleDate = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        TitleHour = new javax.swing.JLabel();
        Hour = new javax.swing.JTextField();
        Title3 = new javax.swing.JLabel();
        IdEmpl = new javax.swing.JLabel();
        IdEmployer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NameEmploy = new javax.swing.JTextField();
        btmAdda = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 51, 0));
        Title.setText("Visitor registration");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 29, 280, 40));

        VisitorFName.setText("First Name:");
        getContentPane().add(VisitorFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 196, 80, -1));

        VisitorLName.setText("Last Name:");
        getContentPane().add(VisitorLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 242, -1, -1));

        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });
        getContentPane().add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 196, 340, -1));
        getContentPane().add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 242, 340, -1));

        Title2.setText("Visitor information:");
        getContentPane().add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        TitleIdVis.setText("ID card:");
        getContentPane().add(TitleIdVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        IdVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdVisActionPerformed(evt);
            }
        });
        getContentPane().add(IdVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 340, -1));

        TitleDate.setText("Date (dd/mm/yy):");
        getContentPane().add(TitleDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 298, -1, -1));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 318, 130, -1));

        TitleHour.setText("Hour:");
        getContentPane().add(TitleHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 298, -1, -1));
        getContentPane().add(Hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 318, 120, -1));

        Title3.setText("Employer information:");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 364, -1, -1));

        IdEmpl.setText("Employer's ID:");
        getContentPane().add(IdEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));
        getContentPane().add(IdEmployer, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 394, 240, -1));

        jLabel7.setText("Employer's name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 446, -1, -1));
        getContentPane().add(NameEmploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 440, 240, -1));

        btmAdda.setText("Add");
        getContentPane().add(btmAdda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void IdVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdVisActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        frmRegister frmRegister = new frmRegister();
        this.setVisible (false);
        frmRegister.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisitorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisitorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisitorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisitorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisitorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField Hour;
    private javax.swing.JLabel IdEmpl;
    private javax.swing.JTextField IdEmployer;
    private javax.swing.JTextField IdVis;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField NameEmploy;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel TitleDate;
    private javax.swing.JLabel TitleHour;
    private javax.swing.JLabel TitleIdVis;
    private javax.swing.JLabel VisitorFName;
    private javax.swing.JLabel VisitorLName;
    private javax.swing.JButton btmAdda;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
