/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.zoo.view;

/**
 *
 * @author User
 */
public class FrmTrakingOrder extends javax.swing.JFrame {

    /**
     * Creates new form FrmCreateOrder
     */
    public FrmTrakingOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "PP6547", "PEDRO PEREZ", "VEGETARIANA", "PERSONAL", "$14,90", "ENTREGADO"},
                {"02", "LR6548", "LUIS RAMIREZ", "CLASICA", "PERSONAL", "$15,60", "ENTREGADO"},
                {"03", "JY6549", "JUAN YEPEZ", "ESPECIAL", "FAMILIAR", "$30,41", "ENTREGADO"},
                {"04", "MA6550", "MARIA ALVAREZ", "PEPPERONI", "FAMILIAR", "$20,45", "ENTREGADO"},
                {"05", "PG6551", "PEDRO GOMEZ", "AFRICANA", "FAMILIAR", "$25,36", "ENTREGADO"},
                {"06", "EL6552", "EDISON LASCANO", "CHICKEN", "JUMBO", "$10,50", "ENTREGADO"},
                {"07", "MC6553", "MARISOL CAMPOS", "ARTESANAL", "JUMBO", "$8,50", "ENTREGADO"},
                {"08", "JL6554", "JENNIFER LOPEZ", "ESPECIAL", "JUMBO", "$8,79", "ENTREGADO"},
                {"09", "FR6555", "FABRICIO REYES", "CHICKEN", "FIESTERA", "$45,80", "ENTREGADO"},
                {"10", "DE6556", "DIEGO ESPIN", "FOUR STATION", "FIESTERA", "$49,30", "PENDIENTE"},
                {"11", "KM6557", "KIMBERLY MORALES", "ESPECIAL", "FIESTERA", "$52,30", "PENDIENTE"},
                {"12", "CS6558", "CAMILO SUAREZ", "ESPECIAL", "FAMILIAR", "$21,10", "ENTREGADO"},
                {"13", "PL6559", "PABLO LLERENA", "CLASICA", "JUMBO", "$8,50", "PENDIENTE"},
                {"14", "JN6560", "JEFFERSON NUÑEZ", "CLASICA", "FIESTERA", "$42,34", "PENDIENTE"},
                {"15", "MS6561", "MATEO SILVA", "VEGETARIANA", "PERSONAL", "$14,30", "ENTREGADO"},
                {"16", "WB6562", "WALTER BENAVIDES", "HAWAYANA", "PERSONAL", "$13,56", "PENDIENTE"},
                {"17", "AC6563", "AGUSTIN CEPEDA", "AFRICANA", "FAMILIAR", "$21,90", "ENTREGADO"}
            },
            new String [] {
                "ORDER", "CODE", "USER NAME", "DETAIL", "TYPE", "COST", "DETAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 570, 270));

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("TRAKING ORDER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, 70));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO DE PIZZA2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 522));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrakingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrakingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrakingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrakingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrakingOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
